#!/bin/sh
#
# Pantoufle - a netboot package manager (c) 2011 Frederic Pasteleurs
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program or from the site that you downloaded it
# from; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA  02111-1307   USA
#
ME=$(basename $0)

### FIXME: Config option ###
SOCKDIR="./$ME.d"
NETBOOTDIR="./NETBOOT"
### /FIXME ###

# Function to call when we bail out
die ()
{
    echo "$ME: $1" 
    if [ "_$2" = "_" ]; then
	exit 1
	else
	exit $2
    fi
}

TMPDIR=$(mktemp -d /tmp/$ME.XXXXXXXXXX)

test -d $NETBOOTDIR || mkdir $NETBOOTDIR || die "Cannot create target directory"

echo "$ME: Fetching files..."
for i in $(ls -1 $SOCKDIR/*.sock|sort); do
    $i GET $TMPDIR
done

echo "$ME: Unpacking files..."
for i in $(ls -1 $SOCKDIR/*.sock|sort); do
    $i UNPACK $TMPDIR $NETBOOTDIR
done

echo "$ME: Building menu"
for i in $(ls -1 $SOCKDIR/*.sock|sort); do
    $i CONFIG
done


# Final cleanup
#rm -rf $TMPDIR
